# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haven < Formula
  desc "Deploy open-source LLMs to your own cloud with one command"
  homepage "https://github.com/yuritur/haven"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuritur/haven/releases/download/v0.0.4/haven_0.0.4_darwin_amd64.tar.gz"
      sha256 "4e0417bd08cfc782315a4c8528ed8d7ce44dcc1ddbcd937655da1568b75bb0d0"

      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuritur/haven/releases/download/v0.0.4/haven_0.0.4_darwin_arm64.tar.gz"
      sha256 "ddbc3484f644d6358a472357f2a3aac5008196f2b66cf3e56ca25964491f4030"

      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.4/haven_0.0.4_linux_amd64.tar.gz"
      sha256 "9eef6972ddb37ba99555535d7a0e055d53fce83031722ce1fdd088b8c2b99977"
      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.4/haven_0.0.4_linux_arm64.tar.gz"
      sha256 "6cbeeedc190c089250746fc970c72681423647fda54b6615f4c41b55b7f2336f"
      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  test do
    system "#{bin}/haven", "--version"
  end
end
