# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haven < Formula
  desc "Deploy open-source LLMs to your own cloud with one command"
  homepage "https://github.com/yuritur/haven"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuritur/haven/releases/download/v0.0.2/haven_0.0.2_darwin_amd64.tar.gz"
      sha256 "a467fe9997d1fd123937b238d0f6dd21a41e0f99ce39803ad20402f69e104f89"

      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuritur/haven/releases/download/v0.0.2/haven_0.0.2_darwin_arm64.tar.gz"
      sha256 "d9ece3f7288af26341e540dd4c02a66e81a7ebded8b0527174a3d27a3760f108"

      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.2/haven_0.0.2_linux_amd64.tar.gz"
      sha256 "83fdf620cba37dd2386acdd27d5e56f84b101623b424a832fe50551cb68d9af6"
      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.2/haven_0.0.2_linux_arm64.tar.gz"
      sha256 "c253fe41be1655c126e93f39b8e406785b16c446f674ea63b78676fd823aa697"
      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  test do
    system "#{bin}/haven", "--version"
  end
end
