# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Haven < Formula
  desc "Deploy open-source LLMs to your own cloud with one command"
  homepage "https://github.com/yuritur/haven"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yuritur/haven/releases/download/v0.0.3/haven_0.0.3_darwin_amd64.tar.gz"
      sha256 "36cfb80d51bb89f2753b79d2b129192b87dc7a9e3bdcfe91856d6141c7b7c3bf"

      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yuritur/haven/releases/download/v0.0.3/haven_0.0.3_darwin_arm64.tar.gz"
      sha256 "7f7e3cbacca2f0e2d474d7e1f6e33baed1f16d2e2aba6bccb5691b47b57b06d7"

      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.3/haven_0.0.3_linux_amd64.tar.gz"
      sha256 "930cf11388434d5ab5fd9cbef656964fd3357c418f0b3b648b06286c0562fc86"
      define_method(:install) do
        bin.install "haven"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuritur/haven/releases/download/v0.0.3/haven_0.0.3_linux_arm64.tar.gz"
      sha256 "45a419892080b4ef15e0d21c6ea2cf060092e8c6d687435a3232a8bb4a469193"
      define_method(:install) do
        bin.install "haven"
      end
    end
  end

  test do
    system "#{bin}/haven", "--version"
  end
end
